# Generated by Django 4.2 on 2023-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(max_length=1000)),
                ('starting_price', models.PositiveIntegerField(max_length=1000000)),
                ('current_price', models.PositiveIntegerField(max_length=1000000)),
                ('cuttoff_price', models.PositiveIntegerField(max_length=1000000)),
                ('current_price_diff_perc', models.IntegerField()),
            ],
        ),
    ]
