# Generated by Django 4.2 on 2023-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0003_product_added_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='starting_price',
            new_name='initial_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='cuttoff_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
