# Generated by Django 4.2 on 2023-05-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0004_rename_starting_price_product_initial_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_price_diff_perc',
            new_name='amount_discount',
        ),
    ]
